# File generated by CompCert 3.4
# Command line: -O2 -S -o __compcert_i64_dtou.s -I./c c/__compcert_i64_dtou.c
	.option nopic
	.text
	.balign 2
	.globl __compcert_i64_dtou
__compcert_i64_dtou:
	mv	x30, x2
	addi	x2, x2, -16
	sw	x30, 0(x2)
	sw	x1, 4(x2)
	fsd	f10, 8(x2)
	lw	x10, 8(x2)
	lw	x5, 12(x2)
	bge	x5, x0, .L100
	addi	x11, x0, 0
	addi	x10, x0, 0
	j	.L101
.L100:
	lui	x31, 524032
	and	x11, x5, x31
	srli	x13, x11, 20
	addi	x12, x13, -1075
	addi	x31, x0, -52
	bge	x12, x31, .L102
	addi	x11, x0, 0
	addi	x10, x0, 0
	j	.L101
.L102:
	addi	x31, x0, 12
	blt	x12, x31, .L103
	addi	x11, x0, -1
	addi	x10, x0, -1
	j	.L101
.L103:
	lui	x31, 256
	addi	x31, x31, -1
	and	x6, x5, x31
	lui	x31, 256
	or	x11, x6, x31
	bge	x12, x0, .L104
	sub	x12, x0, x12
	call	__compcert_i64_shr
	j	.L101
.L104:
	call	__compcert_i64_shl
.L101:
	lw	x1, 4(x2)
	addi	x2, x2, 16
	jr	x1
	.type	__compcert_i64_dtou, @function
	.size	__compcert_i64_dtou, . - __compcert_i64_dtou
