# File generated by CompCert 3.4
# Command line: -O2 -S -o __compcert_i64_sdiv.s -I./c c/__compcert_i64_sdiv.c
	.option nopic
	.text
	.balign 2
	.globl __compcert_i64_sdiv
__compcert_i64_sdiv:
	mv	x30, x2
	addi	x2, x2, -32
	sw	x30, 0(x2)
	sw	x1, 4(x2)
	sw	x8, 8(x2)
	sw	x9, 12(x2)
	mv	x9, x11
	mv	x8, x13
	bge	x9, x0, .L100
	sltu	x1, x0, x10
	sub	x10, x0, x10
	sub	x11, x0, x11
	sub	x11, x11, x1
.L100:
	bge	x8, x0, .L101
	sltu	x1, x0, x12
	sub	x12, x0, x12
	sub	x13, x0, x13
	sub	x13, x13, x1
.L101:
	addi	x14, x2, 16
	call	__compcert_i64_udivmod
	xor	x5, x9, x8
	bge	x5, x0, .L102
	sltu	x1, x0, x10
	sub	x10, x0, x10
	sub	x11, x0, x11
	sub	x11, x11, x1
.L102:
	lw	x8, 8(x2)
	lw	x9, 12(x2)
	lw	x1, 4(x2)
	addi	x2, x2, 32
	jr	x1
	.type	__compcert_i64_sdiv, @function
	.size	__compcert_i64_sdiv, . - __compcert_i64_sdiv
