# File generated by CompCert 3.4
# Command line: -O2 -S -o __compcert_i64_sar.s -I./c c/__compcert_i64_sar.c
	.option nopic
	.text
	.balign 2
	.globl __compcert_i64_sar
__compcert_i64_sar:
	mv	x30, x2
	addi	x2, x2, -16
	sw	x30, 0(x2)
	sw	x1, 4(x2)
	mv	x5, x11
	andi	x12, x12, 63
	beq	x12, x0, .L100
	addi	x31, x0, 32
	bge	x12, x31, .L101
	srl	x7, x10, x12
	addi	x10, x0, 32
	sub	x13, x10, x12
	sll	x6, x5, x13
	or	x10, x7, x6
	sra	x11, x5, x12
	j	.L100
.L101:
	addi	x12, x12, -32
	sra	x10, x5, x12
	srai	x11, x10, 31
.L100:
	lw	x1, 4(x2)
	addi	x2, x2, 16
	jr	x1
	.type	__compcert_i64_sar, @function
	.size	__compcert_i64_sar, . - __compcert_i64_sar
